### ISSUE TITLE
Inconsistency between paper and code

### ISSUE THREAD

**Issue by zyc573823770** [google-research/pix2seq#10]
It seems that the labels in output target are either rand or fake, without any ground truth in it which is different from the paper in the end of section 2.3 that  _After noise objects are synthesised and discretized, we then **append** them in the end of the original input sequence_.

https://github.com/google-research/pix2seq/blob/6d45f77fcbb1905aca3e42678a2a079907ad17d0/tasks/object_detection.py#L399
![image](https://user-images.githubusercontent.com/42412854/167727337-70035f7c-9a8f-4558-8be5-a171980c0f5c.png)

**Comment by zyc573823770** [comment]
![image](https://user-images.githubusercontent.com/42412854/167730295-df27c6aa-f30c-48d3-9186-9ae26f28bf0d.png)

**Comment by chentingpc** [comment]
apologies for late reply. The `response_seq_class_m` is used for the input sequence (the stuff that transformer decoder sees), the label/target sequence (the stuff that transformer decoder is asked to predict) is from `response_seq` which is either real tokens or fake class token. hope that clarifies it.

**Comment by huimlight** [comment]
> apologies for late reply. The `response_seq_class_m` is used for the input sequence (the stuff that transformer decoder sees), the label/target sequence (the stuff that transformer decoder is asked to predict) is from `response_seq` which is either real tokens or fake class token. hope that clarifies it.

Why do I randomly change the label of the Input Sequence? I don't really understand.
