### ISSUE TITLE
Question about inference

### ISSUE THREAD

**Issue by ejlee95** [google-research/pix2seq#14]
I have a question about inference code.

In tasks/task_utils.py, function 'decode_object_seq_to_bbox',
there is no function that acts as 'end-of-sequence'.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/36064879/177670822-192f9c61-6164-4865-a383-dc5fd79fd9a0.png">

I think PADDING_TOKEN (which denoted as 0 in vocab.py) is the token that indicates end-of-seq,
but in the inference time, the code does not use the token.

Am I right?

**Comment by chentingpc** [comment]
yes padding token is also the ending token. with sequence augmentation, we won't use ending token, rather predict to maximum length, and use likelihood to score each instance/prediction.

**Comment by thomas0809** [comment]
Hi Ting,

Thanks for the great research work and the code. In the paper, you mentioned the prediction of a maximum length at inference. I didn't find it in the code. Could you please point me to where it is implemented?

**Comment by chentingpc** [comment]
Please see
https://github.com/google-research/pix2seq/blob/83089ca98e077dd0a6864c2a68583b474df7a2d4/models/ar_model.py#L171

**Comment by thomas0809** [comment]
Thanks for the prompt reply! I misunderstood your paper: I thought you were predicting an actual length of the generated sequence, but actually it is "predict **to** a maximum length".

Did you do any filtering based on the likelihood scores for the evaluation? Otherwise, the model is predicting the same number of objects for all images?

**Comment by chentingpc** [comment]
We rank the prediction using the likelihood score during evaluation (AP
takes a ranked list to compute)
