### ISSUE TITLE
coco images downloading

### ISSUE THREAD

**Issue by Epiphqny** [google-research/pix2seq#2]
Could you please provide the TFDS  COCO image path and the local save path? The dataset can not be downloaded online in my country. Or, how to use the official coco images downloaded from the official website for training, can you provide some instructions?

**Comment by Epiphqny** [comment]
Hi @chentingpc, here are the errors:

`2022-03-30 11:22:01.918943: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
2022-03-30 11:23:03.969272: E tensorflow/core/platform/cloud/curl_http_request.cc:614] The transmission  of request 0x558aa82c61b0 (URI: https://www.googleapis.com/storage/v1/b/tfds-data/o/dataset_info%2Fcoco%2F2017%2F1.1.0?fields=size%2Cgeneration%2Cupdated) has been stuck at 0 of 0 bytes for 61 seconds and will be aborted. CURL timing information: lookup time: 0.095498 (No error), connecttime: 0 (No error), pre-transfer time: 0 (No error), start-transfer time: 0 (No error)`

**Comment by Epiphqny** [comment]
The error disappears after I downgrade the tfds version according to  https://github.com/tensorflow/datasets/issues/2761, thanks for your reply.

**Comment by JulioZhao97** [comment]
Hi! thanks for the comment!
Unfortunately I an in China so tfds.load fails always not matter how I try. So could you please tell me where the dataset is downloaded to? I plan to download from google cloud manually and put data under right folder.

**Comment by isksjsksk** [comment]
I have the same issue and it still remain after I downgrade my tensorflow-datasets version.
