### ISSUE TITLE
About ViT-B

### ISSUE THREAD

**Issue by JerryLauzzz** [google-research/pix2seq#20]
Hi, 

have you ever tried to train ViT-B without Obj365 pretraining?

**Comment by chentingpc** [comment]
We didn't train ViT-B from scratch on COCO, I can imagine it can also work
if the backbone is pretrained on imagenet (like typical object detection
models) and also train with strong augmentation. But we haven't compared.
Pretrained on Object365 from scratch (without imagenet pretraining) is
easier to set up for us and can also initialize the decoder.

**Comment by JerryLauzzz** [comment]
Thanks for the reply.
Yes, imagenet pretrain can indeed work. I am just curious about the performance gap if using imagenet pretrain.
