### ISSUE TITLE
Input Sequence Box Augmentation

### ISSUE THREAD

**Issue by ShijieVVu** [google-research/pix2seq#30]
Did you include the source code for noised gt box and hallucinated box augmentation described in the paper? 
I can only find class augmentation's code. 
Thanks!

**Comment by chentingpc** [comment]
https://github.com/google-research/pix2seq/blob/f213f3a8eda5590b261343026f4a4c951da58638/data/data_utils.py#L326

**Comment by ShijieVVu** [comment]
Thanks for pointing out!
