### ISSUE TITLE
Convert mask to polygon

### ISSUE THREAD

**Issue by zkyseu** [google-research/pix2seq#45]
Hi, I have a question that how you convert the instance mask to polygon in your code? I find that codes used to generate polygons ：
```
polygons = example['image/object/segmentation'].to_tensor(
        default_value=vocab.PADDING_FLOAT,
        shape=[None, max_points * 2])
```
but this codes do not contain instance mask from the given label. so how do you convert given instance mask label to a polygon? Thanks!

**Comment by saxenasaurabh** [comment]
The coco dataset provides the polygons. Please see https://cocodataset.org/#format-data

**Comment by gg22mm** [comment]
Do you have a more detailed explanation, just switching between datasets?
