### ISSUE TITLE
RIN training with float16/bfloat16

### ISSUE THREAD

**Issue by nicolas-dufour** [google-research/pix2seq#47]
I've been trying to train RIN with mixed precision, but it fails for some reason.
Have you tried to train with mixed precision? If so, would you happen to have some recommendations to stabilize training?

Thanks!

![image](https://github.com/google-research/pix2seq/assets/33259879/40ca1667-5c2d-4d89-9df8-18dc72bb5378)
Left: bfloat16; right: float32

**Comment by chentingpc** [comment]
Our model was not trained in float16.

**Comment by nicolas-dufour** [comment]
Ok thanks
