### ISSUE TITLE
speed too slow

### ISSUE THREAD

**Issue by jinfagang** [google-research/pix2seq#5]
takes about 3 mins doesn't get result:

![image](https://user-images.githubusercontent.com/21303438/165888136-219a4872-9bd7-4c26-9cc4-7b533a977328.png)

**Comment by chentingpc** [comment]
the code in colab is currently not run in eager mode so it will download and load the model when it is first run.

we haven't properly compared the inference time with DETR, but the speed difference depends on a few things such as encoder vs decoder's compute portion (for large images encoder may take more time), the number of objects to generate (autoregressive model could take significantly longer when predicting lots of objects, or longer sequences).

**Comment by chenxwh** [comment]
> the code in colab is currently not run in eager mode so it will download and load the model when it is first run.

@chentingpc,

Hi, is there a way to download and load the model prior to the first inference so even the first run can be fast enough?

Thank you!

**Comment by chentingpc** [comment]
I'm not sure what'd be the best way to speed up model download in Google colab. But if you're running on a local machine, you could try to use `gsutil cp -r gs://cloud_folder local_folder` to download manually which may be faster.
