### ISSUE TITLE
checksum error for downloaded data

### ISSUE THREAD

**Issue by dipendra009** [google-research/pix2seq#7]
Hi,
I am getting some checksum error when the code automatically downloads from google bucket. Here is the error message:

 File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/core/download/download_manager.py", line 343, in _handle_download_result
    raise NonMatchingChecksumError(resource.url, tmp_path)
tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact http://images.cocodataset.org/zips/test2017.zip, downloaded to /root/tensorflow_datasets/downloads/images.cocodataset.org_zips_test2017KDQv8bPgQock_hnrTxvqZbYabAXdY4EN91CL7w8_GTo.zip.tmp.86dbce4c6d70492c9e71a03288cf434e/test2017.zip, has wrong checksum. This might indicate:
 * The website may be down (e.g. returned a 503 status code). Please check the url.
 * For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL. See https://github.com/tensorflow/datasets/issues/1482
 * The original datasets files may have been updated. In this case the TFDS dataset builder should be updated to use the new files and checksums. Sorry about that. Please open an issue or send us a PR with a fix.
 * If you're adding a new dataset, don't forget to register the checksums as explained in: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally

Could you please update the checksum so that we can use the code.

Regards,
Dipendra

**Comment by chentingpc** [comment]
Thanks for reporting the error. This is a quite specific issue with dataset download module of `tensorflow_datasets`, so I'm not sure how much I'm able to help. As suggested in the error message, you could try to download the coco dataset manually to bypass the automatic downloading function of `tensorflow_datasets` which is causing the issue. Maybe before that, you could try something even simpler: delete the existing coco dataset files downloaded by `tensorflow_datasets`.
